version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: tetris-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=https://api.tetris.adelinemeistertzheim.fr/api
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: tetris-backend
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_INTERNAL_PORT}"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: tetris-db
    restart: always
    environment:
      POSTGRES_USER: tetris_user
      POSTGRES_PASSWORD: tetris_pass
      POSTGRES_DB: tetris_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    container_name: tetris-adminer
    restart: always
    ports:
      - "127.0.0.1:8081:8080" # exposition locale uniquement, Ã  atteindre via tunnel SSH
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

volumes:
  postgres_data:
